[project]
name = "mlx-inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mlx>=0.22.0",
    "pydantic>=2.10.5",
    "tokenizers>=0.21.0",
]
